dist: bionic
sudo: false
language: c
apt:
    - gcc-multilib
    - linux-libc-dev
    - binutils-arm-none-eabi
    - wine
install:
    # These files are only accessible from Travis CI IP Addresses to prevent piracy.
    - wget http://private.martmists.com/mwccarm.zip
    - wget http://private.martmists.com/baserom.nds
    - wget http://private.martmists.com/nitro.zip
    - unzip mwccarm.zip
    - mv mwccarm tools
    - unzip nitro.zip
    - mv Nitro\ SDK\ 3.0/tools/bin tools
    - mv Nitro\ SDK\ 3.0/include/nitro/specfiles/ARM7-TS.lcf.template arm7
    - mv Nitro\ SDK\ 3.0/include/nitro/specfiles/ARM9-TS.lcf.template arm9

script:
    - export LM_LICENSE_FILE="$(pwd)/tools/mwccarm/license.dat"
    - make

notifications:
  email: false
