dist: bionic
sudo: false
language: c
env:
    global:
        - LM_LICENSE_FILE="$TRAVIS_BUILD_DIR/tools/mwccarm/license.dat"
addons:
    apt:
        packages:
            - gcc-multilib
            - linux-libc-dev
            - binutils-arm-none-eabi
            - wine32
            - wine-stable
            - jq
cache:
    apt: true
install:
    # These files are only accessible from Travis CI IP Addresses to prevent piracy.
    - wget http://private.martmists.com/mwccarm.zip
    - wget http://private.martmists.com/nitro.tar.gz
    - unzip mwccarm.zip
    - mv mwccarm tools
    - tar xzvf nitro.tar.gz
    - mv NitroSDK-3_2-060901/tools/bin tools
    - mv NitroSDK-3_2-060901/include/nitro/specfiles/ARM7-TS.lcf.template arm7
    - mv NitroSDK-3_2-060901/include/nitro/specfiles/ARM9-TS.lcf.template arm9

script:
    - make

notifications:
  email: false

after_success:
    - .travis/calcrom/webhook.sh pokediamond
