dist: bionic
sudo: require
language: c
env:
    global:
        - LM_LICENSE_FILE="$TRAVIS_BUILD_DIR/tools/mwccarm/license.dat"
addons: &gcc9
    apt:
        packages:
            - gcc-multilib
            - linux-libc-dev
            - binutils-arm-none-eabi
            - wine32
            - wine-stable
            - gcc-9
            - g++-9
cache:
    apt: true
install:
    # These files are only accessible from Travis CI IP Addresses to prevent piracy.
    - wget http://private.martmists.com/mwccarm.zip
    - wget http://private.martmists.com/baserom.nds
    - wget http://private.martmists.com/nitro.zip
    - unzip mwccarm.zip
    - mv mwccarm tools
    - unzip nitro.zip
    - mv NITRO\ SDK\ v3.0/tools/bin tools
    - mv NITRO\ SDK\ v3.0/include/nitro/specfiles/ARM7-TS.lcf.template arm7
    - mv NITRO\ SDK\ v3.0/include/nitro/specfiles/ARM9-TS.lcf.template arm9

script:
    - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
    - make

notifications:
  email: false

after_success:
    - .travis/calcrom/webhook.sh pokediamond
